In [1]:
import numpy as np
import pandas as pd

In [2]:
##### numpy arrays: more compact (and therefore more memory efficient) than python lists. 
##### unlike python lists, numpy is constrained to arrays that all contain the same type.

In [3]:
# create a numpy array as below
np.random.seed(0)
arr = np.array(np.random.normal(size=(3,5)))
arr

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799],
       [-0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ],
       [ 0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323]])

In [4]:
# print elements in column 1
arr[:,1] 

array([0.40015721, 0.95008842, 1.45427351])

In [5]:
# print elements in row 0
arr[0,:] 
# arr[0]

array([1.76405235, 0.40015721, 0.97873798, 2.2408932 , 1.86755799])

In [6]:
# print element at row 0 and column 1
arr[0,1] # multi-dimensional indexing
# arr[0][1] # chained indexing

0.4001572083672233

In [7]:
# print elements in columns 1 and 3
arr[:,[1,3]] 

array([[ 0.40015721,  2.2408932 ],
       [ 0.95008842, -0.10321885],
       [ 1.45427351,  0.12167502]])

In [8]:
# print elements in rows 0 and 2
arr[[0,2],:] 
# arr[[0,2]]

array([[1.76405235, 0.40015721, 0.97873798, 2.2408932 , 1.86755799],
       [0.14404357, 1.45427351, 0.76103773, 0.12167502, 0.44386323]])

In [9]:
# print elements in rows 0 and 2 & columns 1 and 3
arr[np.ix_([0,2],[1,3])] 

array([[0.40015721, 2.2408932 ],
       [1.45427351, 0.12167502]])

In [10]:
### define a 3 x 5 array, and min-max scale each row
np.random.seed(10)
nr, nc = 3, 5
arr = np.random.randint(0, 100, 15).reshape(nr, nc)
arr

array([[ 9, 15, 64, 28, 89],
       [93, 29,  8, 73,  0],
       [40, 36, 16, 11, 54]])

In [11]:
# get row-wise mins
rmin = np.min(arr, axis=1).reshape(nr,1)
rmin

array([[ 9],
       [ 0],
       [11]])

In [12]:
# get row-wise maxs
rmax = np.max(arr, axis=1).reshape(nr,1)
rmax

array([[89],
       [93],
       [54]])

In [13]:
# min-max scale
mmsarr = (arr - rmin) / (rmax - rmin)
np.round(mmsarr, 2)

array([[0.  , 0.08, 0.69, 0.24, 1.  ],
       [1.  , 0.31, 0.09, 0.78, 0.  ],
       [0.67, 0.58, 0.12, 0.  , 1.  ]])