In [169]:
# Reference: 
# online free docs:          https://docs.scipy.org/doc/numpy/
#                                     https://docs.scipy.org/doc/numpy/user/basics.types.html
#                                     https://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs
# book old edition free:  https://www.safaribooksonline.com/library/view/python-data-science/9781491912126/
# book new edition pay: https://smile.amazon.com/Python-Data-Science-Handbook-Essential/dp/1491912057/

In [170]:
# NumPy Arrays are more compact (and therefore more memory efficient) than Python Lists.
# Unlike Python Lists, NumPy is constrained to arrays that all contain the same type.

In [171]:
import numpy as np

In [187]:
##### aggregations #####

np.random.seed(10)
data = np.random.randint(0, 100, 10)

print (data)
print (np.sum(data))      # data.sum()
print (np.min(data))      # data.min()
print (np.argmin(data)) # index of min value # data.argmin()
print (np.max(data))      # data.max()
print (np.argmax(data)) # index of max value # data.argmax()
print (np.mean(data))    # data.mean()
print (np.median(data)) # data.median() doesn't work!
print (np.std(data))        # data.std()
print (np.var(data))        # data.var()
print (np.percentile(data,10)) # 10th percentile
print (np.any(data))       # evaluate if any element is true # data.any()
print (np.all(data))        # evaluate if all elements are true # data.all()

# for 2D arrays, can either aggregate over entire data or aggregate across rows/columns
data = data.reshape(2,5)
print (data)
print (np.sum(data, axis=0)) 
print (np.sum(data, axis=1))

[ 9 15 64 28 89 93 29  8 73  0]
408
0
9
93
5
40.8
28.5
33.68026128164685
1134.36
7.2
True
False
[[ 9 15 64 28 89]
 [93 29  8 73  0]]
[102  44  72 101  89]
[205 203]


In [188]:
##### universal functions (or ufuncs) #####

np.random.seed(1)
data = np.arange(1,10)
print (data)

print (np.exp(data))        # e^x
print (np.exp2(data))       # 2^x
print (np.power(3, data))   # 3^x

print (np.log(data))        # ln(x)
print (np.log2(data))       # log2(x)
print (np.log10(data))      # log10(x)

print (np.sin(data))
print (np.cos(data))

[1 2 3 4 5 6 7 8 9]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]
[  2.   4.   8.  16.  32.  64. 128. 256. 512.]
[    3     9    27    81   243   729  2187  6561 19683]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026]


In [189]:
##### conditional selection #####

# you can use any comparison operator:  ==  !=  >  >=  <  <=
data = np.arange(1, 20, 2)
print (data)
print (data > 5)
print (data[data > 5])

# comparisons work on arrays of any dimension
data = np.arange(9).reshape(3,3)
print (data >= 3)

# comparisons also work bit-wise on two arrays
a = np.array([1, 2, 3, 40, 50])
b = np.array([10, 20, 3, 4, 5])
print (a > b)

# comparisons work with bitwise logic operators: &  |  ^
data= np.arange(9)
print (data)
print ((data > 3) & (data < 9))
print ((data > 3) | (data == 0))
print ((data > 3) ^ (data != 0))

[ 1  3  5  7  9 11 13 15 17 19]
[False False False  True  True  True  True  True  True  True]
[ 7  9 11 13 15 17 19]
[[False False False]
 [ True  True  True]
 [ True  True  True]]
[False False False  True  True]
[0 1 2 3 4 5 6 7 8]
[False False False False  True  True  True  True  True]
[ True False False False  True  True  True  True  True]
[False  True  True  True False False False False False]


In [190]:
##### arithmetic operations #####

# array with scalar arithmetic operations  +, -, *, /, ** (uses broadcast)
data= np.arange(1,10).reshape(3,3)
print (data)
print (-data)       # shorthand for np.negative(data)
print (1 / data)    # shorthand for np.reciprocal(data.astype(float))
print (data + 5)    # shorthand for np.add(data, 5)
print (data - 5)    # shorthand for np.subtract(data, 5)
print (data * 2)    # shorthand for np.multiply(data, 2)
print (data / 2)    # shorthand for np.divide(data, 2)
print (data ** 2)   # shorthand for np.power(data, 2)
print (data % 2)    # shorthand for np.mod(data, 2)
print (data // 2)   # shorthand for np.floor_divide(data, 2)
print (np.absolute(-data))

# array with array arithmetic operations +, -, *, /, ** (operates on corresponding elements)
x = np.arange(0,5)
y = np.arange(5,10)
print (x)
print (y)
print (x+y)
print (x-y)
print (x*y)
print (x/y)
print (x**y)
print (x%y)
print (x//y)

# broadcasting use case: normalization
data = np.random.randint(0,100,10)
dm = data.mean()
ds = data.std()
print (data)
print (dm, ds)
norm = (data-dm)/ds
nm = norm.mean()
ns = norm.std()
print (norm)
print (nm, ns)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-1 -2 -3]
 [-4 -5 -6]
 [-7 -8 -9]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]
 [0.14285714 0.125      0.11111111]]
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[-4 -3 -2]
 [-1  0  1]
 [ 2  3  4]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[1 0 1]
 [0 1 0]
 [1 0 1]]
[[0 1 1]
 [2 2 3]
 [3 4 4]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[0 1 2 3 4]
[5 6 7 8 9]
[ 5  7  9 11 13]
[-5 -5 -5 -5 -5]
[ 0  6 14 24 36]
[0.         0.16666667 0.28571429 0.375      0.44444444]
[     0      1    128   6561 262144]
[0 1 2 3 4]
[0 0 0 0 0]
[37 12 72  9 75  5 79 64 16  1]
37.0 30.548322376196047
[ 0.         -0.81837555  1.14572576 -0.91658061  1.24393083 -1.0475207
  1.37487092  0.88384559 -0.68743546 -1.17846079]
2.2204460492503132e-17 0.9999999999999999
