In [2]:
# Reference: 
# online free docs:          https://docs.scipy.org/doc/numpy/
#                                     https://docs.scipy.org/doc/numpy/user/basics.types.html
#                                     https://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs
# book old edition free:  https://www.safaribooksonline.com/library/view/python-data-science/9781491912126/
# book new edition pay: https://smile.amazon.com/Python-Data-Science-Handbook-Essential/dp/1491912057/

In [3]:
# NumPy Arrays are more compact (and therefore more memory efficient) than Python Lists.
# Unlike Python Lists, NumPy is constrained to arrays that all contain the same type.

In [4]:
import numpy as np

In [5]:
##### creating numpy arrays #####

In [6]:
# use a list
arr1D = np.array([1,2,3])
print (arr1D)
arr2D = np.array([[1,2,3],[4,5,6]])
print (arr2D)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [7]:
# use arange
arr1D = np.arange(10)
print (arr1D)
arr1D = np.arange(1, 10)
print (arr1D)
arr1D = np.arange(1,10, 2)
print (arr1D)

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [8]:
# linspace
arr1D = np.linspace(0, 10, 5)
print (arr1D)
arr1D = np.linspace(1, 10, 5)
print (arr1D)
arr1D = np.linspace(1, 10, 10)
print (arr1D)

[ 0.   2.5  5.   7.5 10. ]
[ 1.    3.25  5.5   7.75 10.  ]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [9]:
# empty: doesn't initialize to zeros
arr1D = np.empty(10) # 1D
print (arr1D)
arr2D = np.empty((2,3)) # 2D
print(arr2D)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
# zeros
arr1D = np.zeros(10) # 1D
print (arr1D)
arr2D = np.zeros((3,5)) #2D
print (arr2D)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
# ones
arr1D = np.ones(10) # 1D
print (arr1D)
arr2D = np.ones((3,5)) #2D
print (arr2D)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [12]:
# full
arr1D = np.full(10, 3.14) # 1D
print (arr1D)
arr2D = np.full((3,5), 3.14) #2D
print (arr2D)

[3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]
[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]


In [13]:
# eye (identity)
arr2D = np.eye(5, dtype=int) #2D
print (arr2D)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [16]:
# random

# set random seed
np.random.seed(0)

# uniform distribution over ``[0, 1)
arr1D = np.random.rand(3) 
print (arr1D)
arr2D = np.random.rand(3,5) 
print (arr2D)

# normal distribution with mean 0 and std dev 1 (can change this using loc and scale parameters)
arr1D = np.random.normal(size=3) 
print (arr1D)
arr2D = np.random.normal(size=(3,5)) 
print (arr2D)
arr1D = np.random.normal(0, 1, 10) 
print (np.mean(arr1D), np.std(arr1D))
arr1D = np.random.normal(0, 1, 1000000) 
print (np.mean(arr1D), np.std(arr1D))

# discrete uniform distribution in [low, high) - if low and high specified - or [0, low) - if only low specified
arr1D = np.random.randint(0, 10, 3) 
print (arr1D)
arr2D = np.random.randint(0, 10, (3,5)) 
print (arr2D)

[0.5488135  0.71518937 0.60276338]
[[0.54488318 0.4236548  0.64589411 0.43758721 0.891773  ]
 [0.96366276 0.38344152 0.79172504 0.52889492 0.56804456]
 [0.92559664 0.07103606 0.0871293  0.0202184  0.83261985]]
[0.44386323 0.33367433 1.49407907]
[[-0.20515826  0.3130677  -0.85409574 -2.55298982  0.6536186 ]
 [ 0.8644362  -0.74216502  2.26975462 -1.45436567  0.04575852]
 [-0.18718385  1.53277921  1.46935877  0.15494743  0.37816252]]
-0.3785675336793436 0.9869512657294515
0.001502544955090189 0.9999145536339031
[6 1 8]
[[3 1 8 1 1]
 [7 2 7 6 8]
 [7 3 3 1 2]]


In [17]:
# some useful array attributes
data = np.random.randint(1,100, (3,5))
print (data)
print (data.ndim, data.shape, data.size, data.dtype)

[[49 78 89 73 15]
 [90 12 13 28 49]
 [82 21 40 38 12]]
2 (3, 5) 15 int32


In [18]:
# reshape 
data = np.arange(10)
print (data)
data = data.reshape(2,5)
print (data)
data = np.arange(15).reshape(3,5)
print (data)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [19]:
# indexing and slicing

arr1D = np.arange(1, 40, 2)
print (arr1D)
print (arr1D[2:5])
print (arr1D[2:])
print (arr1D[:4])

arr2D = arr1D.reshape(4,5)
print (arr2D)
print (arr2D[1])
print (arr2D[1][3])
print (arr2D[1,3])
print (arr2D[1:3,2:4])

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39]
[5 7 9]
[ 5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39]
[1 3 5 7]
[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]]
[11 13 15 17 19]
17
17
[[15 17]
 [25 27]]


In [20]:
# arrays have fixed type

data = np.arange(10)

print (data)
data[2] = 3.141 
print (data)

data = data.astype(float)
data[2] = 3.141
print (data)

[0 1 2 3 4 5 6 7 8 9]
[0 1 3 3 4 5 6 7 8 9]
[0.    1.    3.141 3.    4.    5.    6.    7.    8.    9.   ]


In [21]:
# arrays are mutable
data = np.arange(10)
print (data)
data[2] = 400
print (data)

# name object bindings hold here as well
data = np.arange(10)
databind = data
print (data)
print (databind)
data[0] = 5555
print (data)
print (databind)

data = np.arange(10)
datacopy = data.copy()
print (data)
print (datacopy)
data[0] = 5555
print (data)
print (datacopy)

[0 1 2 3 4 5 6 7 8 9]
[  0   1 400   3   4   5   6   7   8   9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[5555    1    2    3    4    5    6    7    8    9]
[5555    1    2    3    4    5    6    7    8    9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[5555    1    2    3    4    5    6    7    8    9]
[0 1 2 3 4 5 6 7 8 9]
